/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-poll`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/interest`; params?: Router.UnknownInputParams; } | { pathname: `/invite-code`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/phone-number`; params?: Router.UnknownInputParams; } | { pathname: `/poll`; params?: Router.UnknownInputParams; } | { pathname: `/profile-photo`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/username`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/constants/categories`; params?: Router.UnknownInputParams; } | { pathname: `/constants/global`; params?: Router.UnknownInputParams; } | { pathname: `/context/CategoryContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/auth`; params?: Router.UnknownInputParams; } | { pathname: `/mocks/polls`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create-poll`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/interest`; params?: Router.UnknownOutputParams; } | { pathname: `/invite-code`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/phone-number`; params?: Router.UnknownOutputParams; } | { pathname: `/poll`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-photo`; params?: Router.UnknownOutputParams; } | { pathname: `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/username`; params?: Router.UnknownOutputParams; } | { pathname: `/pending`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/global`; params?: Router.UnknownOutputParams; } | { pathname: `/context/CategoryContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/mocks/polls`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/create-poll${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/interest${`?${string}` | `#${string}` | ''}` | `/invite-code${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/phone-number${`?${string}` | `#${string}` | ''}` | `/poll${`?${string}` | `#${string}` | ''}` | `/profile-photo${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `/username${`?${string}` | `#${string}` | ''}` | `/pending${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/constants/categories${`?${string}` | `#${string}` | ''}` | `/constants/global${`?${string}` | `#${string}` | ''}` | `/context/CategoryContext${`?${string}` | `#${string}` | ''}` | `/context/auth${`?${string}` | `#${string}` | ''}` | `/mocks/polls${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-poll`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/interest`; params?: Router.UnknownInputParams; } | { pathname: `/invite-code`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/phone-number`; params?: Router.UnknownInputParams; } | { pathname: `/poll`; params?: Router.UnknownInputParams; } | { pathname: `/profile-photo`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/username`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/constants/categories`; params?: Router.UnknownInputParams; } | { pathname: `/constants/global`; params?: Router.UnknownInputParams; } | { pathname: `/context/CategoryContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/auth`; params?: Router.UnknownInputParams; } | { pathname: `/mocks/polls`; params?: Router.UnknownInputParams; };
    }
  }
}
